# Form implementation generated from reading ui file 'design/design.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Widgets(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 453)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 631, 281))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.user_message = QtWidgets.QLineEdit(parent=self.tab)
        self.user_message.setGeometry(QtCore.QRect(0, 290, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.user_message.setFont(font)
        self.user_message.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"}")
        self.user_message.setObjectName("user_message")
        self.send_message_btn = QtWidgets.QPushButton(parent=self.tab)
        self.send_message_btn.setGeometry(QtCore.QRect(0, 350, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.send_message_btn.setFont(font)
        self.send_message_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.send_message_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: gray;\n"
"}")
        self.send_message_btn.setObjectName("send_message_btn")
        self.quit_from_chat = QtWidgets.QPushButton(parent=self.tab)
        self.quit_from_chat.setGeometry(QtCore.QRect(330, 350, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quit_from_chat.setFont(font)
        self.quit_from_chat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.quit_from_chat.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: gray;\n"
"}")
        self.quit_from_chat.setObjectName("quit_from_chat")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.server_ip = QtWidgets.QLineEdit(parent=self.tab_2)
        self.server_ip.setGeometry(QtCore.QRect(0, 0, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.server_ip.setFont(font)
        self.server_ip.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"}")
        self.server_ip.setObjectName("server_ip")
        self.server_port = QtWidgets.QLineEdit(parent=self.tab_2)
        self.server_port.setGeometry(QtCore.QRect(0, 60, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.server_port.setFont(font)
        self.server_port.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"}")
        self.server_port.setObjectName("server_port")
        self.user_nikname = QtWidgets.QLineEdit(parent=self.tab_2)
        self.user_nikname.setGeometry(QtCore.QRect(0, 120, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.user_nikname.setFont(font)
        self.user_nikname.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    background: white;\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"}")
        self.user_nikname.setObjectName("user_nikname")
        self.save_settings_btn = QtWidgets.QPushButton(parent=self.tab_2)
        self.save_settings_btn.setGeometry(QtCore.QRect(0, 180, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.save_settings_btn.setFont(font)
        self.save_settings_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_settings_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: gray;\n"
"}")
        self.save_settings_btn.setObjectName("save_settings_btn")
        self.connect_to_server_btn = QtWidgets.QPushButton(parent=self.tab_2)
        self.connect_to_server_btn.setGeometry(QtCore.QRect(320, 180, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.connect_to_server_btn.setFont(font)
        self.connect_to_server_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.connect_to_server_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background: gray;\n"
"}")
        self.connect_to_server_btn.setObjectName("connect_to_server_btn")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AChat"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "Тут будуть ваші повідомлення та повідомлення інших користувачів"))
        self.user_message.setPlaceholderText(_translate("MainWindow", "Введіть повідомлення"))
        self.send_message_btn.setText(_translate("MainWindow", "Відправити"))
        self.quit_from_chat.setText(_translate("MainWindow", "Вийти з  чату"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Чат"))
        self.server_ip.setPlaceholderText(_translate("MainWindow", "IP сервера"))
        self.server_port.setPlaceholderText(_translate("MainWindow", "Порт сервера"))
        self.user_nikname.setPlaceholderText(_translate("MainWindow", "Ваш нікнейм"))
        self.save_settings_btn.setText(_translate("MainWindow", "Зберегти налаштування"))
        self.connect_to_server_btn.setText(_translate("MainWindow", "Підключитися до сервера"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Налаштування"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Widgets()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
